### ISSUE TITLE
MIT License or some other license?

### ISSUE THREAD

**Issue by icedwater** [TaoRuijie/SpeakerVerificationDemo#1]
The parent repository is using an MIT license. Can we assume that this repo is also licensed to MIT?

**Comment by TaoRuijie** [comment]
I think so. I just simply that repository to make it easier to be used as a 'demo'. The code is all related to "https://github.com/clovaai/voxceleb_trainer ".

**Comment by icedwater** [comment]
Thanks for your reply! I'll add a LICENSE file in to make it explicit.
