### ISSUE TITLE
problem in demoSpeakerNet

### ISSUE THREAD

**Issue by LeonTheRench** [TaoRuijie/SpeakerVerificationDemo#2]
I wanted to test the demo recognition with my test audios, but an error occured the Warning goes below:
Traceback (most recent call last):
  File "E:\SpeakerRecognitionDemo-main\demoSpeakerNet.py", line 53, in <module>
    score = [float(numpy.round(-torch.nn.functional.pairwise_distance(feat_enroll.unsqueeze(-1), feat_test.unsqueeze(-1).transpose(0,2)).detach().numpy(), 4))]
TypeError: only size-1 arrays can be converted to Python scalars

I didnt change the code, can you help?

**Comment by TaoRuijie** [comment]
Please check the path for the file.

The code is for ubuntu, usually the path is splitted by '/', for windows, the path is splitted by '\\' or '\'. So you need to check the path format

**Comment by LeonTheRench** [comment]
> Please check the path for the file.
> 
> The code is for ubuntu, usually the path is splitted by '/', for windows, the path is splitted by '\' or ''. So you need to check the path format

thank you for your advice. I will try it later
