### ISSUE TITLE
nable to execute

### ISSUE THREAD

**Issue by Liuyuhung** [TaoRuijie/SpeakerVerificationDemo#3]
Traceback (most recent call last):
  File "demoSpeakerNet.py", line 53, in <module>
    score = [float(numpy.round(- torch.nn.functional.pairwise_distance(feat_enroll.unsqueeze(-1), feat_test.unsqueeze(-1).transpose(0,2)).detach().numpy(), 4))]
TypeError: only size-1 arrays can be converted to Python scalars

**Comment by namho-96** [comment]
I change from feat_enroll.unsqueeze(-1), feat_test.unsqueeze(-1).transpose(0,2) to feat_enroll, feat_test. And then it works.

**Comment by Liuyuhung** [comment]
Thank you very much, it can be executed smoothly
